/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alex1
 */
public class frmPrueba extends javax.swing.JFrame {

    /**
     * Creates new form frmPrueba
     */
    public frmPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFrenos = new javax.swing.JButton();
        btnAlineamiento = new javax.swing.JButton();
        btnNeumaticos = new javax.swing.JButton();
        btnLuces = new javax.swing.JButton();
        btnEmisionesSonoras = new javax.swing.JButton();
        btnSuspension = new javax.swing.JButton();
        btnEmisionGases = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Bottom.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1050, -1));

        btnFrenos.setBackground(new java.awt.Color(255, 255, 255));
        btnFrenos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnFrenos.setForeground(new java.awt.Color(51, 51, 51));
        btnFrenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frenos.png"))); // NOI18N
        btnFrenos.setText("Frenos");
        btnFrenos.setBorder(null);
        btnFrenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFrenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frenos_2.png"))); // NOI18N
        btnFrenos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnFrenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        btnAlineamiento.setBackground(new java.awt.Color(255, 255, 255));
        btnAlineamiento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAlineamiento.setForeground(new java.awt.Color(51, 51, 51));
        btnAlineamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alineamiento-de-ruedas.png"))); // NOI18N
        btnAlineamiento.setText("Alineamiento");
        btnAlineamiento.setBorder(null);
        btnAlineamiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlineamiento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alineamiento-de-ruedas_2.png"))); // NOI18N
        btnAlineamiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnAlineamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        btnNeumaticos.setBackground(new java.awt.Color(255, 255, 255));
        btnNeumaticos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNeumaticos.setForeground(new java.awt.Color(51, 51, 51));
        btnNeumaticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rueda.png"))); // NOI18N
        btnNeumaticos.setText("Neumaticos");
        btnNeumaticos.setBorder(null);
        btnNeumaticos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNeumaticos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rueda_2.png"))); // NOI18N
        btnNeumaticos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnNeumaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

        btnLuces.setBackground(new java.awt.Color(255, 255, 255));
        btnLuces.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLuces.setForeground(new java.awt.Color(51, 51, 51));
        btnLuces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/faros-del-coche.png"))); // NOI18N
        btnLuces.setText("Luces");
        btnLuces.setBorder(null);
        btnLuces.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLuces.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/faros-del-coche_2.png"))); // NOI18N
        btnLuces.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnLuces, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        btnEmisionesSonoras.setBackground(new java.awt.Color(255, 255, 255));
        btnEmisionesSonoras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEmisionesSonoras.setForeground(new java.awt.Color(51, 51, 51));
        btnEmisionesSonoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ondas-sonoras.png"))); // NOI18N
        btnEmisionesSonoras.setText("Emisiones sonoras");
        btnEmisionesSonoras.setBorder(null);
        btnEmisionesSonoras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmisionesSonoras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ondas-de-sonido_2.png"))); // NOI18N
        btnEmisionesSonoras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnEmisionesSonoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        btnSuspension.setBackground(new java.awt.Color(255, 255, 255));
        btnSuspension.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSuspension.setForeground(new java.awt.Color(51, 51, 51));
        btnSuspension.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/suspension.png"))); // NOI18N
        btnSuspension.setText("Suspensión");
        btnSuspension.setBorder(null);
        btnSuspension.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuspension.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/suspension_2.png"))); // NOI18N
        btnSuspension.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnSuspension, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        btnEmisionGases.setBackground(new java.awt.Color(255, 255, 255));
        btnEmisionGases.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEmisionGases.setForeground(new java.awt.Color(51, 51, 51));
        btnEmisionGases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tubo-de-escape.png"))); // NOI18N
        btnEmisionGases.setText("Emisión de Gases");
        btnEmisionGases.setBorder(null);
        btnEmisionGases.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmisionGases.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tubo-de-escape_2.png"))); // NOI18N
        btnEmisionGases.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnEmisionGases, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 183, 156));
        jLabel2.setText("Pruebas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlineamiento;
    public javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEmisionGases;
    private javax.swing.JButton btnEmisionesSonoras;
    private javax.swing.JButton btnFrenos;
    private javax.swing.JButton btnLuces;
    private javax.swing.JButton btnNeumaticos;
    private javax.swing.JButton btnSuspension;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
